### ISSUE TITLE
How to make it work with wordpress

### ISSUE THREAD

**Issue by cliftonc0613** [ramswaroop/animatescroll.js#12]
Hello!

I love your plugin! My question is how do you make the onclick even work with wordpress? 

I actually found this http://designm.ag/tutorials/single-page-dynamic-website-using-animatescrolljs/ 

but cant get it to work

Thanks

**Comment by alexandrogiles** [comment]
It's simple, the easiest way is to load jquery:
In functions.php of your theme add (between <?php  ?> tags:  
wp_enqueue_script('jquery');

Then on header.php of your theme (or footer.php) :
<script src="<?php bloginfo('template_url'); ?>/path-to-your-js-folder/animatedscroll.js
example:
<?php bloginfo('template_url'); ?>/js/animatedscroll.js 

then just add 
 <a onclick="$('[jquery selector]').animatescroll([options]);">Go to Element</a> as usually.

Regards.

**Comment by ramswaroop** [comment]
@cliftonc0613 Is your issue solved or need any help? Closing this as its not an issue with the plugin.
