### ISSUE TITLE
Update on usage (data-animate-scroll)

### ISSUE THREAD

**Issue by srph** [ramswaroop/animatescroll.js#13]
Instead of

```javascript
<a onclick="$('[jquery selector]').animatescroll([options]);">Go to Element</a>
```

We might as well make use of ```data-animate-scroll``` in which the library listen for ```on-click``` events on elements having the data attribute? For example,

```
<a href="#" data-animate-scroll-target=".that-element" data-animate-scroll-ease="swing"></a>
```

**Comment by ramswaroop** [comment]
I thought of using the data api earlier but due to lack of time I wasn't able to add, anyways I will be adding support for them soon.

If you're comfortable with javascript, you can even contribute by sending a pull request.
