### ISSUE TITLE
Padding option

### ISSUE THREAD

**Issue by JoseJoaoMata** [ramswaroop/animatescroll.js#16]
Hi! 
Great plugin, especially for its simplicity!

I have a small problem or am I doing something wrong. I have a script to keep the DIV where I have the navigation, always at the top of the window, when I scroll, I need to always leave space for that div.
Then I thought using the padding option, however it only works on the second click. The first click it scroll to the exact position of the element, and only when I give another click is that it sets the padding.
I try to invoke the function that keeps my navigation on top with the option "onScrollEnd", but it didn't work either.

It is normal behavior, or should be something else?
Thank you very much!
Jose

**Comment by ramswaroop** [comment]
Can you create a jsfiddle describing your issue and provide the link here?
